name = "utt-admissions-be"
main = "./dist/worker.js"
compatibility_date = "2026-05-02"
compatibility_flags = [
  "nodejs_compat",
  "enable_nodejs_http_modules",
  "enable_nodejs_http_server_modules"
]
keep_vars = true

[build]
command = "npm run build"
